### PR TITLE
Add support for application mime-type & remove redundant files

### PR DESCRIPTION
**Pull request by abarisic86**

### CODE REVIEW

**Comment by arribbar** [comment]
Sorry @abarisic86. Is it still up to date ?
I'll update my PR to be merged in alinz repo instead

**Comment by abarisic86** [comment]
It's used in production for our app.

**Comment by arribbar** [comment]
Great. Can you just update the conflicted file ?

**Comment by arribbar** [comment]
And if you can update Readme file to know how to use your new functionality. It would be great. It seems there is a new contributor in alinz project, ready to help us and merge new PRs :)

**Comment by abarisic86** [comment]
@Taarna <https://github.com/Taarna> can you help with this?

**Comment by Taarna** [comment]
> @Taarna <https://github.com/Taarna> can you help with this?

I'll take a look over the weekend

**Comment by arribbar** [comment]
If this PR https://github.com/alinz/react-native-share-extension/pull/84 is merged, it is better to create another PR to master project

**Pull request closed without merging**
